sudo: required

language: java

notifications:
    slack: ifrs-engsoftware3:z5WVXZtPYKLLFoNmpTwL24ty

services:
  -  docker
  
before_install:
  -  docker build -t fizzbuzz/junit .
  
script:
  -  cd my-app/
  -  docker run fizzbuzz/junit /bin/sh -c "mvn package; mvn clean test;"