sudo: required

language: java

notifications:
    slack: ifrs-engsoftware3:z5WVXZtPYKLLFoNmpTwL24ty

services:
  -  docker
  
before_install:
  -  docker build -t fizzbuzz/junit .
  
script:
  -  docker run fizzbuzz/junit /bin/sh -c "cd my-app/; mvn package; mvn clean test;"